# Generated by Django 3.2.5 on 2021-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos')),
                ('desc', models.TextField()),
                ('Nickname', models.TextField()),
                ('name1', models.BooleanField(default=False)),
                ('Nickname1', models.BooleanField(default=False)),
                ('desc1', models.BooleanField(default=False)),
                ('release1', models.BooleanField(default=False)),
                ('logo1', models.BooleanField(default=False)),
            ],
        ),
    ]
